Handle signup scenario where a user already exists
Mojtabarezaei4/Queueomatic pull request #132
Opened 2023-06-08 17:35 UTC by Mojtabarezaei4

Close #131 and also close #126

2023-06-08 19:31 UTC, FabianAronsson requested changes
Looks good, but I think the text response message should be in hue of red and also centered.

2023-06-08 19:59 UTC, Mojtabarezaei4 commented
> Looks good, but I think the text response message should be in hue of red and also centered.

I find it hard to read in that tone of color because of the background. The current is meant to match the one on the login page.

2023-06-08 22:43 UTC, FabianAronsson commented
> > Looks good, but I think the text response message should be in hue of red and also centered.
> 
> I find it hard to read in that tone of color because of the background. The current is meant to match the one on the login page.

Why not use a toast or a banner then?

2023-06-12 10:12 UTC, FabianAronsson approved these changes

2023-06-12 14:08 UTC, merged